config/routes.rb
WritingWorkshop::Application.routes.draw do

  devise_for :users

  root :to => 'welcome#index'

  resources :stories

  resources :readings, except: [:show] do
    post 'comment'
  end

  resources :paragraphs, only: [:index] do
    post 'like'
    post 'unlike'
    post 'comment'
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  attr_accessible :comment
end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  belongs_to :story
  attr_accessible :body

  acts_as_votable
  acts_as_commentable
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :user
  attr_accessible :link

  acts_as_commentable
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body, :title
  has_many :paragraphs

  acts_as_commentable


  def paragraph_it
    text = self.body
    array = text.split("\r\n")
    array.each do |p|
      if p.length > 0
        paragraph = Paragraph.new
        paragraph.body = p
        paragraph.story = self
        paragraph.save
      end
    end
  end

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :stories
  has_many :readings

  acts_as_voter

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  def index
  end

  def show
    @paragraph = Paragraph.find(params[:paragraph_id])
    @comments = @paragraph.comments
    @comment = Comment.new
  end

  def like
    @paragraph = Paragraph.find(params[:paragraph_id])
    @paragraph.liked_by current_user

    respond_to do |format|
      format.html { redirect_to @paragraph.story }
      format.js
    end
  end

  def unlike
    @paragraph = Paragraph.find(params[:paragraph_id])
    @paragraph.unliked_by current_user

    respond_to do |format|
      format.html { redirect_to @paragraph.story }
      format.js
    end
  end

  def comment
    @paragraph = Paragraph.find(params[:paragraph_id])
    @comment = @paragraph.comments.create(params[:comment])
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.html { redirect_to @paragraph.story }
      format.js
    end
  end

end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_filter :check_user

  def index
    @readings = Reading.all
    @comment = Comment.new
  end

  def new
    @reading = Reading.new
  end

  def create
    @reading = current_user.readings.create(params[:reading])

    if @reading
      flash[:notice] = "Reading added."
      redirect_to root_path
    else
      flash[:error] = "Reading didn't add for some reason. Please try again."
      render :new
    end
  end

  def edit
  end

  def comment
    @reading = Reading.find(params[:reading_id])
    @comment = @reading.comments.create(params[:comment])
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  
  def check_user
    if current_user
      return true
    else
      flash[:notice] = "Please login"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  before_filter :check_user

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @paragraphs = @story.paragraphs
    @comment = Comment.new
  end

  def new
    @story = Story.new
  end

  def create
    @story = current_user.stories.create(params[:story])

    if @story
      flash[:notice] = "Story saved."
      @story.paragraph_it
      redirect_to @story
    else
      flash[:error] = "Story didn't save for some reason. Please try again."
      render :new
    end 
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])

    @story.update_attributes(params[:story])

    if @story.save
      flash[:notice] = "Story updated."
    else
      flash[:error] = "Story didn't update for some reason. Please try again."
    end
  end


  def check_user
    if current_user
      return true
    else
      flash[:notice] = "Please login"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @stories = Story.all
    @readings = Reading.all
    @comment = Comment.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

   <title><%= content_for?(:title) ? yield(:title) : "Harvard School of Vengeance" %></title> 


    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "Harvard School of Vengeance", root_path %></h1>
          </li>
        </ul>
        <section class="top-bar-section">
          <ul class="right">
            <li class= "has-form">
              <%= link_to "Post Story", new_story_path, class: 'button', style: "margin-top: 8px" %>
            </li>
            <li class="divider"></li>
            <% if current_user %>
              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign Up", new_user_registration_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign In", new_user_session_path %>
              </li>
            <% end %> 
          </ul>
        </section>
      </nav>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/paragraphs/_comment.html.erb
<p><%= comment.comment %>
<small>by <%= comment.user.email %></small>
</p>

app/views/paragraphs/_comment_form.html.erb
<%= form_for @comment, url: paragraph_comment_path(paragraph), remote: true do |f| %>
  <%= f.text_area :comment, rows: "4", placeholder: "Add comment", autofocus: true %>
  <%= f.submit "Submit", class: "button tiny" %>
<% end %>

app/views/paragraphs/_like.html.erb
<%= link_to "Like", paragraph_like_path(paragraph), remote:true, method: :post %>
<% if paragraph.votes_for.count > 0 %>
  (<%= paragraph.votes_for.count %>)
<% end %>

app/views/paragraphs/_paragraph.html.erb
<div class="row">

  <div class="small-1 large-1 columns">
    <div id="<%= paragraph.id %>-like">
      <% if current_user.voted_for? paragraph %>
      <!-- the ajax renders these partials also -->
      <%= render partial: "paragraphs/unlike", locals: { paragraph: paragraph } %>
      <% else %>
      <%= render partial: "paragraphs/like", locals: { paragraph: paragraph } %>
      <% end %>
    </div>
  </div>

  <div class="small-6 large-6  columns">
    <p><%= paragraph.body %></p>
    <!-- like/unlike button -->
  </div>

  <div class="small-5 large-4 large-offset-1 columns">
    <div id="<%= paragraph.id %>-comments">
      <% if paragraph.comments.count > 0 %>
      <%= render partial: "paragraphs/comment", collection: paragraph.comments %>
      <% end %>
    </div>
    <a href="#" class="js-show-hide" data-selector="<%= paragraph.id %>-comment-form">Add Comment</a>
    <div class="<%= paragraph.id %>-comment-form hide">
      <%= render partial: "paragraphs/comment_form", locals: { paragraph: paragraph } %>
    </div>
  </div>


</div>

app/views/paragraphs/_unlike.html.erb
<%= link_to "Unlike", paragraph_unlike_path(paragraph), remote: true, method: :post %>
<% if paragraph.votes_for.count > 0 %>
  (<%= paragraph.votes_for.count %>)
<% end %>

app/views/paragraphs/comment.js.erb
$("#<%= @paragraph.id %>-comments").html("<%= j render partial: 'paragraphs/comment', collection: @paragraph.comments %>");
$(".<%= @paragraph.id %>-comment-form").slideUp();

app/views/paragraphs/index.html.erb
<h1>Paragraphs#index</h1>
<p>Find me in app/views/paragraphs/index.html.erb</p>

app/views/paragraphs/like.js.erb
$("#<%= @paragraph.id %>-like").html("<%= j render partial: 'paragraphs/unlike', locals: { paragraph: @paragraph  } %>")

app/views/paragraphs/show.html.erb
<p><%= @paragraph.body %></p>
<%= form_for @comment do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.submit "Submit" %>
<% end %>

app/views/paragraphs/unlike.js.erb
$("#<%= @paragraph.id %>-like").html("<%= j render partial: 'paragraphs/like', locals: { paragraph: @paragraph  } %>")

app/views/readings/_comment_form.html.erb
<%= form_for @comment, url: reading_comment_path(reading) do |f| %>
  <%= f.text_area :comment, rows: "4", placeholder: "Add comment", autofocus: true %>
  <%= f.submit "Submit", class: "button tiny" %>
<% end %>

app/views/readings/_reading.html.erb
<p><a href="<%= reading.link.html_safe %>", target=_blank><%= reading.link %></a>
  <small>submitted by <%= reading.user.email %></small>
</p>
<%= render partial: "paragraphs/comment", collection: reading.comments %>
<%= render partial: "readings/comment_form", locals: { reading: reading } %>

app/views/readings/edit.html.erb
<h1>Readings#edit</h1>
<p>Find me in app/views/readings/edit.html.erb</p>

app/views/readings/index.html.erb
<h1>Readings#index</h1>
<p>Find me in app/views/readings/index.html.erb</p>

app/views/readings/new.html.erb
<h1>Post a new reading</h1>

<%= form_for @reading do |f| %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit "Submit" %>
<% end %>

app/views/stories/_story.html.erb
<p><%= link_to story.title, story %></p>

app/views/stories/edit.html.erb
<h1>Stories#edit</h1>
<p>Find me in app/views/stories/edit.html.erb</p>

app/views/stories/index.html.erb
<h1>Stories#index</h1>
<p>Find me in app/views/stories/index.html.erb</p>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Submit" %>
<% end %>

app/views/stories/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1><%= @story.title %></h1>
    <%= render @paragraphs %>
  </div> 
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3>Stories</h3>
      <%= render @stories %>
    <h3>Required Reading</h3>
      <%= link_to "New Reading", new_reading_path %>
      <%= render @readings %>
  </div>
</div>